@devhost=https://localhost:7107
@prodhost=https://optimus-verden-venter.azurewebsites.net/


POST {{devhost}}/api/categories
Content-Type: application/json

{
  "name": "Styrke",
  "emoji": "💪"
}

###

POST {{prodhost}}/api/categories
Content-Type: application/json

{
  "name": "Fotball2",
  "emoji": "⚽"
}