@devhost=https://localhost:7107
@prodhost=https://verdenventer.azurewebsites.net

@id=b96f5471-4e3a-4256-2c0c-08da96149036

DELETE {{devhost}}/api/categories/{{id}}

###

DELETE {{prodhost}}/api/categories/{{id}}