@devhost=https://localhost:7107
@prodhost=https://verdenventer.azurewebsites.net

@id=3e061bac-93c0-46b9-a502-08da96e466d8

GET {{devhost}}/api/categories/{{id}}

###

GET {{prodhost}}/api/categories/{{id}}