@id=8d478fbe-ea5b-44b7-ebc1-08daaa918de8

PUT {{host}}/api/categories/{{id}}
Content-Type: application/json
Authorization: Bearer {{admintoken}}
# Authorization: Bearer {{usertoken}}

{
  "name": "SkatePark",
  "emoji": "🛹"
}