@devhost=https://localhost:7107
@prodhost=https://verdenventer.azurewebsites.net
@id=0d870839-a74d-4293-2124-08da8fe1d9b8

PUT {{devhost}}/api/categories/{{id}}
Content-Type: application/json

{
  "name": "Fotball",
  "emoji": "⚽"
}

###

PUT {{prodhost}}/api/categories/{{id}}
Content-Type: application/json

{
  "name": "Fotball23",
  "emoji": "⚽"
}