POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "verden.venter.app@gmail.com",
  "password": "123123123"
}

###

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "jdoe@email.com",
  "password": "123123123"
}