POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "12345qwerty",
  "firstname": "Admin",
  "lastname": "Adminson",
  "DOB": "2000-01-29",
  "favoritecategoryIds": []
}

###

POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "user3@email.com",
  "password": "12345qwerty",
  "firstname": "User",
  "lastname": "Userdottir",
  "DOB": "2000-02-27",
  "favoritecategoryIds": []
}