POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "123123123",
  "firstname": "Admin",
  "lastname": "Adminson",
  "DOB": "2000-01-29",
  "favoritecategoryIds": []
}

###

POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "jdoe@email.com",
  "password": "123123123",
  "firstname": "John",
  "lastname": "Doe",
  "DOB": "2000-02-27",
  "favoritecategoryIds": ["f7e9d7ff-7091-43ca-4b4c-08daddb21d12"]
}