POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "user@email.com",
  "password": "12345qwerty",
  "firstname": "User",
  "lastname": "Userdottir",
  "DOB": "2022-10-06",
  "favoritecategoryIds": []
}