POST {{host}}/api/users/role
Content-Type: application/json
Authorization: Bearer {{admintoken}}

{
  "userId": "f1c8c9b1-f4fa-4927-ae3f-39aa0c61f082",
  "roleId": "f4e24c36-162b-4df2-420d-08dab8b3a485"
}