POST {{host}}/api/users/role
Content-Type: application/json
Authorization: Bearer {{admintoken}}

{
  "userId": "6281e1e8-3d85-45b8-bba2-594dbf2969cb",
  "roleId": "04571743-0a86-45f5-901a-08daa13f9828"
}