@id=7ee03ccb-89b1-411d-9b7c-a9e1ed8048ba

PUT {{host}}/api/users/{{id}}
# Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="firstname"

testing Jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lastname"

Helt OK skatepark med betong elementer.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address"

5.12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="postalarea"

58.12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="postalcode"

9a6415fa-57dd-4698-dabf-08daaabaac26
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="phonenumber"

9a6415fa-57dd-4698-dabf-08daaabaac26
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="dob"

9a6415fa-57dd-4698-dabf-08daaabaac26
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="FavoriteCategoryIds"

9a6415fa-57dd-4698-dabf-08daaabaac26
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="ProfileImage"; filename="notpng.jpeg"
Content-Type: image/jpeg

< ../Assets/notpng.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

PUT {{host}}/api/users/{{id}}
Authorization: Bearer {{usertoken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="ProfileImage"; filename="notpng.jpeg"
Content-Type: image/jpeg

< ../Assets/notpng.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--