@id=1e295e62-4efa-4470-af15-d9ebff887190

PUT {{host}}/api/users/{{id}}
Content-Type: application/json
# Authorization: Bearer {{token}}

{
  "Email": "email567@gmail.com",
  "FirstName": "Email",
  "LastName": "Gmail",
  "Address": "EmailStreet 5",
  "PostalArea": "Stavanger",
  "PostalCode": 4034,
  "PhoneNumber": 87654321,
  "DOB": "1987-04-25",
  "RoleIds": []
}