### Create Location without image

POST {{host}}/api/locations
Authorization: Bearer {{admintoken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Another Location
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

A very long description as it needs 20 chars
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="longitude"

5.3454362342
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="latitude"

58.2345346547
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category"

f7e9d7ff-7091-43ca-4b4c-08daddb21d12
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Create Location With Image

POST {{host}}/api/locations
# Authorization: Bearer {{usertoken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Lura Skatepark
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Helt OK skatepark med betong elementer.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="longitude"

5.12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="latitude"

58.12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category"

f7e9d7ff-7091-43ca-4b4c-08daddb21d12
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="notpng.jpeg"
Content-Type: image/jpeg

< ../Assets/notpng.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--