@devhost=https://localhost:7107
@prodhost=https://verdenventer.azurewebsites.net

@id=b9f1e59d-651e-466e-8df5-56535976c920

DELETE {{devhost}}/api/locations/{{id}}

###

DELETE {{prodhost}}/api/locations/{{id}}