@devhost=https://localhost:7107
@prodhost=https://verdenventer.azurewebsites.net

@id=f2048041-4d45-405e-a81e-0f08ca699125

GET {{devhost}}/api/locations/{{id}}

###

GET {{prodhost}}/api/locations/{{id}}