@devhost=https://localhost:7107
@prodhost=https://optimus-verden-venter.azurewebsites.net/

@id=9fbf46b3-c5a5-450a-9b28-1a3167e2625a

GET {{devhost}}/api/locations/{{id}}

###

GET {{prodhost}}/api/locations/{{id}}