@devhost=https://localhost:7107
@prodhost=https://verdenventer.azurewebsites.net
@latitude=58.1234
@longitude=5.1234
@category=0d870839-a74d-4293-2124-08da8fe1d9b8


GET {{devhost}}/api/locations/{{latitude}}&{{longitude}}/category

###

GET {{devhost}}/api/locations/{{latitude}}&{{longitude}}/category??category={{category}}


###

GET {{prodhost}}/api/locations/{{latitude}}&{{longitude}}/category

###

GET {{prodhost}}/api/locations/{{latitude}}&{{longitude}}/category??category={{category}}