@longitude=5.1234
@latitude=58.1234
@category=3e061bac-93c0-46b9-a502-08da96e466d8


GET {{host}}/api/locations/{{latitude}}&{{longitude}}/category

###

GET {{host}}/api/locations/{{latitude}}&{{longitude}}/category??category={{category}}