@id=8b76584a-ac09-4ca0-88a2-a3cffc2abbae

### Update Location Without Image

PUT {{host}}/api/locations/{{id}}
Authorization: Bearer {{admintoken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

testing updating something
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

A description that's longer than 20 chars!
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="status"

Approved
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category"

f7e9d7ff-7091-43ca-4b4c-08daddb21d12
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Update Location With Image


PUT {{host}}/api/locations/{{id}}
Authorization: Bearer {{admintoken}}
# Authorization: Bearer {{usertoken}}
# Authorization: Bearer {{registrationtoken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="status"

Declined
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="notpng.jpeg"
Content-Type: image/png

< ../Assets/notpng.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--