@locationId=87fcc676-2efd-4f31-956a-672fcdcd9ffa

### Create Review Without Image

POST {{host}}/api/reviews
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="rating"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="locationId"

{{locationId}}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Create Review With Image

POST {{host}}/api/reviews
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="rating"

4
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

Skikkelig bra ja
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="locationId"

{{locationId}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="park.png"
Content-Type: image/png

< ../Images/park.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--