@devhost=https://localhost:7107
@prodhost=https://optimus-verden-venter.azurewebsites.net/

@id=5a2936d2-a958-4e6c-84ea-abb0bdfddcec

DELETE {{devhost}}/api/reviews/{{id}}

###

DELETE {{prodhost}}/api/reviews/{{id}}