@id=f64dc21c-a812-4186-a596-0f0e19b6a52c
@locationId=8e322b1a-5193-47e6-8527-7dd01d61d777

### Update Review Without Image

PUT {{host}}/api/reviews/{{id}}
# Authorization: Bearer {{admintoken}}
Authorization: Bearer {{usertoken}}
# Authorization: Bearer {{registrationtoken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="status"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

oppdatering fra usertoken
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="rating"

3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="locationId"

{{locationId}}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Update Review With Image

PUT {{host}}/api/reviews/{{id}}
# Authorization: Bearer {{admintoken}}
Authorization: Bearer {{usertoken}}
# Authorization: Bearer {{registrationtoken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="status"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

oppdatering fra userToken
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="rating"

3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="locationId"

{{locationId}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="park.png"
Content-Type: image/png

< ../Assets/park.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--