@devhost=https://localhost:7107
@prodhost=https://optimus-verden-venter.azurewebsites.net/
@id=7da7e16e-8b07-4a20-a394-75f3329df06f
@locationId=9fbf46b3-c5a5-450a-9b28-1a3167e2625a

### Dev host without image

PUT {{devhost}}/api/reviews
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id"

{{id}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="status"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="rating"

3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="locationId"

{{locationId}}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Dev host with image

PUT {{devhost}}/api/reviews/{{id}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="status"

Under Review
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

some review text
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="rating"

3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="locationId"

{{locationId}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="img"; filename="park.png"
Content-Type: image/png

< ./park.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

PUT {{prodhost}}/api/reviews
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="status"

Under Review
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

some review text
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="rating"

3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="locationId"

{{locationId}}
0d870839-a74d-4293-2124-08da8fe1d9b8
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="img"; filename="park.png"
Content-Type: image/png

< ./park.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--