@id=ac5c2811-cb94-4113-a4eb-d431642c8331
@locationId=9fbf46b3-c5a5-450a-9b28-1a3167e2625a

### Update Review Without Image

PUT {{host}}/api/reviews
# Authorization: Bearer {{admintoken}}
Authorization: Bearer {{usertoken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id"

{{id}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="status"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="rating"

3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="locationId"

{{locationId}}
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Update Review With Image

PUT {{host}}/api/reviews
Authorization: Bearer {{usertoken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id"

{{id}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="status"

Declined
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

some review text
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="rating"

3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="locationId"

{{locationId}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="park.png"
Content-Type: image/png

< ../Images/park.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--